package com.cjx913.mybatis.pojo;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.PRODUCT_PRICE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    private BigDecimal productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.PRODUCT_PICTURE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    private String productPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT.PRODUCT_REMARK
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    private String productRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.PRODUCT_ID
     *
     * @return the value of T_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.PRODUCT_ID
     *
     * @param productId the value for T_PRODUCT.PRODUCT_ID
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.PRODUCT_NAME
     *
     * @return the value of T_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.PRODUCT_NAME
     *
     * @param productName the value for T_PRODUCT.PRODUCT_NAME
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.PRODUCT_PRICE
     *
     * @return the value of T_PRODUCT.PRODUCT_PRICE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public BigDecimal getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.PRODUCT_PRICE
     *
     * @param productPrice the value for T_PRODUCT.PRODUCT_PRICE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.PRODUCT_PICTURE
     *
     * @return the value of T_PRODUCT.PRODUCT_PICTURE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.PRODUCT_PICTURE
     *
     * @param productPicture the value for T_PRODUCT.PRODUCT_PICTURE
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture == null ? null : productPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT.PRODUCT_REMARK
     *
     * @return the value of T_PRODUCT.PRODUCT_REMARK
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public String getProductRemark() {
        return productRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT.PRODUCT_REMARK
     *
     * @param productRemark the value for T_PRODUCT.PRODUCT_REMARK
     *
     * @mbg.generated Thu Mar 22 10:55:35 CST 2018
     */
    public void setProductRemark(String productRemark) {
        this.productRemark = productRemark == null ? null : productRemark.trim();
    }

    @Override
    public String toString() {
        return "Product{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productPrice=" + productPrice +
                ", productPicture='" + productPicture + '\'' +
                ", productRemark='" + productRemark + '\'' +
                '}';
    }
}