CREATE TEMPORARY TABLESPACE temp_ts_mybatis
TEMPFILE 'E:\IntelliJ IDEA\MybatisDemo\sql\temp_ts_mybatis.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 5M MAXSIZE 10M
EXTENT MANAGEMENT LOCAL ;

CREATE TABLESPACE ts_mybatis
DATAFILE 'E:\IntelliJ IDEA\MybatisDemo\sql\ts_mybatis.dbf'
  SIZE 20M
  AUTOEXTEND ON NEXT 10M MAXSIZE 100M
  EXTENT MANAGEMENT LOCAL ;

CREATE USER cjx913 IDENTIFIED BY cjx913
DEFAULT TABLESPACE ts_mybatis
TEMPORARY TABLESPACE temp_ts_mybatis;

GRANT CONNECT, RESOURCE TO cjx913;